Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-08-04T20:50:16.756468+00:00 [queued]>
Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-08-04T20:50:16.756468+00:00 [queued]>

--------------------------------------------------------------------------------
Starting attempt 2 of 2

--------------------------------------------------------------------------------
Executing <Task(MySqlOperator): create_mysql_table> on 2020-08-04T20:50:16.756468+00:00
Running: ['airflow', 'run', 'store_DAG', 'create_mysql_table', '2020-08-04T20:50:16.756468+00:00', '--job_id', '28', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/store_DAG.py', '--cfg_path', '/tmp/tmptj4nlm55']
Job 28: Subtask create_mysql_table [2020-08-04 20:53:37,262] {{settings.py:213}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=1731
Job 28: Subtask create_mysql_table /usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
Job 28: Subtask create_mysql_table   """)
Job 28: Subtask create_mysql_table [2020-08-04 20:53:40,294] {{__init__.py:51}} INFO - Using executor LocalExecutor
Job 28: Subtask create_mysql_table [2020-08-04 20:53:48,334] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags/store_DAG.py
Job 28: Subtask create_mysql_table [2020-08-04 20:53:49,154] {{cli.py:516}} INFO - Running <TaskInstance: store_DAG.create_mysql_table 2020-08-04T20:50:16.756468+00:00 [running]> on host 6a822f9627d0
Executing: CREATE TABLE IF NOT EXISTS clean_store_transactions(STORE_ID varchar(50), STORE_LOCATION varchar(50), PRODUCT_CATEGORY varchar(50), PRODUCT_ID int, MRP float, CP float, DISCOUNT float, SP float, DATE date);
The conn_id `mysql_conn` isn't defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
    parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
    conn = self.get_connection(self.mysql_conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
    conns = cls._get_connections_from_db(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
    "The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
All retries failed; marking task as FAILED
Job 28: Subtask create_mysql_table Traceback (most recent call last):
Job 28: Subtask create_mysql_table   File "/usr/local/bin/airflow", line 32, in <module>
Job 28: Subtask create_mysql_table     args.func(args)
Job 28: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
Job 28: Subtask create_mysql_table     return f(*args, **kwargs)
Job 28: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
Job 28: Subtask create_mysql_table     _run(args, dag, ti)
Job 28: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
Job 28: Subtask create_mysql_table     pool=args.pool,
Job 28: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
Job 28: Subtask create_mysql_table     return func(*args, **kwargs)
Job 28: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
Job 28: Subtask create_mysql_table     result = task_copy.execute(context=context)
Job 28: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
Job 28: Subtask create_mysql_table     parameters=self.parameters)
Job 28: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
Job 28: Subtask create_mysql_table     with closing(self.get_conn()) as conn:
Job 28: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
Job 28: Subtask create_mysql_table     conn = self.get_connection(self.mysql_conn_id)
Job 28: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
Job 28: Subtask create_mysql_table     conn = random.choice(list(cls.get_connections(conn_id)))
Job 28: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
Job 28: Subtask create_mysql_table     conns = cls._get_connections_from_db(conn_id)
Job 28: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
Job 28: Subtask create_mysql_table     return func(*args, **kwargs)
Job 28: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
Job 28: Subtask create_mysql_table     "The conn_id `{0}` isn't defined".format(conn_id))
Job 28: Subtask create_mysql_table airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
[[34m2020-08-04 20:53:54,188[0m] {{[34mlocal_task_job.py:[0m172}} WARNING[0m - State of this instance has been externally set to [1mfailed[0m. Taking the poison pill.[0m
Sending Signals.SIGTERM to GPID 1731
Process psutil.Process(pid=1731, status='terminated') (1731) terminated with exit code -15
[[34m2020-08-04 20:53:54,614[0m] {{[34mlocal_task_job.py:[0m105}} INFO[0m - Task exited with return code 0[0m
